export enum ActionTypes {
  GET_ALBUM_BY_SLUG = "GET_ALBUM_BY_SLUG",
  GET_ALBUMS = "GET_ALBUMS",
  GET_STORY_BY_SLUG = "GET_STORY_BY_SLUG",
  GET_STORIES = "GET_STORIES",
  SET_MENU_STATE = "SET_MENU_STATE",
  TOGGLE_MENU = "TOGGLE_MENU",
}
